# Site settings
title: "mavroprovato"
email: "mavroprovato@gmail.com"
description: "A small corner at the edge of the internet."
baseurl: ""
url: "mavroprovato.net"
title_description: "A small corner at the edge of the internet."
title_image: "favicons/android-chrome-512x512.png"
google_analytics: "UA-38537171-1"
disqus_account: mavroprovato
github_repository: https://github.com/mavroprovato
addthis_id:
post_limit: 5

# Social usernames/URLs
twitter_username: _mavroprovato
github_username:  mavroprovato
instagram_username:
reddit_username:
linkedin_link: https://www.linkedin.com/in/mavroprovato/
google_plus_link:
stackoverflow_link: https://stackoverflow.com/users/89435/mavroprovato
xing_link:
facebook_link:

# Footer
footer_left: "Template <strike>stolen from</strike> inspired by <a href=\"https://github.com/jacobtomlinson/carte-noire\">Jacob Tomlinson</a>"
footer_right: ""

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
