# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

# Site Settings
locale: "en-US"
title: "mavroprovato"
subtitle: "A small corner at the edge of the internet."
name: "Kostas Kokkoros"
description: "A small corner at the edge of the internet."

# Site Author
author:
  name: "Kostas Kokkoros"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "A small corner at the edge of the internet"
  location: "Athens, Greece"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:mavroprovato@gmail.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.mavroprovato.net"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mavroprovato"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mavroprovato"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/mavroprovato"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/_mavroprovato"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/_mavroprovato"

# Site Footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:mavroprovato@gmail.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.mavroprovato.net"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mavroprovato"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mavroprovato"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/mavroprovato"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/_mavroprovato"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/_mavroprovato"

# Reading Files
include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
